`((user name "Christopher Rodriguez")
  (user email "yewscion@gmail.com")
  (user signingKey "F39C D463 49A5 76F8 8EF9  2479 1102 102E BE7C 3AE4")
  (commit template ,(string-append (getenv "HOME")
                                   "/.emacs/templates/git-commit.txt"))
  (init defaultBranch "trunk")
  (alias glog
         ,(string-append "log --graph --pretty=format:'%Cred%h%Creset "
                         "-%C(yellow)%d%Creset %s %Cgreen(%cr) "
                         "%C(bold blue)<%an>%Creset'"))
  (commit gpgSign "true")
  (http sslCAinfo "/etc/ssl/certs/ca-certificates.crt")
  (sendemail smtpServer ,(string-append (getenv "GUIX_PROFILE") "/bin/msmtp"))
  (sendemail annotate "true")
  (sendemail smtpServerOption "-agmail-yewscion")
  (sendemail smtpEncryption "true")
  (core compression "9")
  (checkout workers "-1")
  (fetch writeCommitGraph "true")
  (grep lineNumber "true")
  (grep column "true")
  (help format "info")
  (pull ff "true")
  (push followTags "true")
  (push negotiate "true")
  (rebase stat "true")
  (status short "true")
  (status branch "true")
  (status showStash "true")
  (stash showPatch "true")
  (tag forceSignAnnotated "true")
  (web browser "icecat")
  (tag gpgSign "true")
  (remotes primary "gorse sourcehut")
  (sendemail from "Christopher Rodriguez <yewscion@gmail.com>"))
