(define my-texlive-packages
  '("texlive-amsfonts" "texlive-babel-russian"
    "texlive-biblatex" "texlive-biblatex-apa" "texlive-booktabs"
    "texlive-capt-of" "texlive-cm" "texlive-csquotes" "texlive-context"
    "texlive-doi" "texlive-enumitem" "texlive-etoolbox" "texlive-fontspec"
    "texlive-fonttable" "texlive-generic-etexcmds"
    "texlive-generic-gettitlestring" "texlive-generic-ifptex"
    "texlive-generic-iftex" "texlive-generic-xstring" "texlive-hyperref"
    "texlive-ifmtarg" "texlive-kpathsea" "texlive-kpfonts"
    "texlive-latex-appendix" "texlive-latex-catchfile"
    "texlive-latex-cleveref" "texlive-latex-comment"
    "texlive-latex-datetime2" "texlive-latex-datetime2-english"
    "texlive-latex-endfloat" "texlive-latex-environ"
    "texlive-latex-everyhook" "texlive-latex-fancyhdr"
    "texlive-latex-fancyvrb" "texlive-latex-float" "texlive-latex-framed"
    "texlive-latex-fvextra" "texlive-latex-geometry" "texlive-latex-graphics"
    "texlive-latex-ifplatform" "texlive-latex-kvoptions"
    "texlive-latex-letltxmacro" "texlive-latex-lineno" "texlive-latex-lipsum"
    "texlive-latex-lwarp" "texlive-latex-memoir" "texlive-latex-minted"
    "texlive-latex-newfloat" "texlive-latex-newunicodechar"
    "texlive-latex-pdftexcmds" "texlive-latex-printlen"
    "texlive-latex-readablecv" "texlive-latex-refcount"
    "texlive-latex-setspace" "texlive-latex-titlesec"
    "texlive-latex-trimspaces" "texlive-latex-type1cm"
    "texlive-latex-upquote" "texlive-latex-venndiagram"
    "texlive-latex-xkeyval" "texlive-latex-xpatch" "texlive-libkpathsea"
    "texlive-luatex-luamplib" "texlive-hologo" "texlive-listings"
    "texlive-lm" "texlive-luaotfload" "texlive-metapost" "texlive-mflogo"
    "texlive-pdfx" "texlive-pgf" "texlive-stringenc" "texlive-svn-prov"
    "texlive-tex-gyre" "texlive-tex-texinfo" "texlive-tracklang"
    "texlive-txfonts" "texlive-unicode-math" "texlive-varwidth"
    "texlive-xcolor" "texlive-xifthen"))
